wip

diff --git a/script/bootstrap b/script/bootstrap
--- a/script/bootstrap
+++ b/script/bootstrap
@@ -1,19 +1,31 @@
 #!/bin/bash
+
 #
 # Sets up all the dependencies, etc. so you can build and test.
 
 set -euo pipefail
 
-# shellcheck source=./utilities.bash
-source "$(dirname "$0")/utilities.bash"
+declare -i success=0 failure=0
 
-header "Fetching utilites"
-go get "$@" -v \
-  gopkg.in/alecthomas/gometalinter.v2 \
-  github.com/mitchellh/gox \
-  github.com/kardianos/govendor
+yes() {
+  success+=1
+  echo '✅ '"$*"
+}
 
-header "Installing gometalinter tools"
-gometalinter.v2 --install
+no() {
+  failure+=1
+  echo '❌ '"$*"
+}
+
+if command -v 'golangci-lint' >/dev/null; then
+  yes 'golangci-lint is present'
+else
+  no 'golangci-lont is missing'
+fi
+
+if ((failure > 0)); then
+  echo "Fix the failures and run again."
+  exit 1
+fi
 
 # vim: set ft=sh :
